name: Build and Push Multi-Arch Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux]
        arch: [amd64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_AUTH_USERNAME }}
          password: ${{ secrets.DOCKERHUB_AUTH_TOKEN }}
      
      
      - name: Build and push image for current architecture
        env:
          DOCKER_BUILDKIT: 1
          DOCKER_CLI_EXPERIMENTAL: enabled
        run: |
          docker build -t docker-multi-arch:${{ matrix.os }}-${{ matrix.arch }} .
          docker push docker-multi-arch:${{ matrix.os }}-${{ matrix.arch }}
      
      - name: Create manifest list
        env:
          DOCKER_CLI_EXPERIMENTAL: enabled
        run: |
          docker manifest create my-image:latest \
            docker-multi-arch:linux-amd64 \
            docker-multi-arch:linux-arm64
          docker manifest push docker-multi-arch:latest
